-- MS Fleet AI Command Center Supabase schema
-- Run this once in the Supabase SQL Editor before enabling Supabase in .env.

create table if not exists raw_messages (
    id bigint generated by default as identity primary key,
    source text not null,
    session text default '',
    group_id text,
    group_name text,
    sender_id text,
    sender_name text,
    message_id text not null,
    message_type text,
    original_text text,
    detected_language text,
    english_translation text,
    timestamp text,
    has_media boolean not null default false,
    media_url text,
    raw_payload text not null,
    processed_status text not null default 'received',
    created_at text not null default now()::text,
    unique(source, session, message_id)
);

create table if not exists groups (
    group_id text primary key,
    group_name text,
    source text,
    first_seen text not null,
    last_seen text not null,
    message_count bigint not null default 0
);

create table if not exists technicians (
    sender_id text primary key,
    sender_name text,
    first_seen text not null,
    last_seen text not null,
    message_count bigint not null default 0
);

create table if not exists jobs (
    job_id text primary key,
    unit_number text,
    customer_name text,
    technician_name text,
    group_name text,
    complaint text,
    diagnosis text,
    repair_performed text,
    parts_used text,
    part_number text,
    quantity numeric,
    status text,
    payment_status text,
    invoice_amount numeric,
    repair_category text,
    confidence_level text,
    confidence_reason text,
    missing_information text,
    last_update_time text,
    created_at text not null,
    updated_at text not null
);

create table if not exists job_events (
    id bigint generated by default as identity primary key,
    job_id text references jobs(job_id) on delete set null,
    raw_message_id bigint not null references raw_messages(id) on delete cascade,
    event_type text,
    summary text,
    extraction_json text not null,
    confidence_level text,
    confidence_reason text,
    created_at text not null
);

create table if not exists parts (
    id bigint generated by default as identity primary key,
    job_id text references jobs(job_id) on delete set null,
    raw_message_id bigint not null references raw_messages(id) on delete cascade,
    part_name text,
    part_number text,
    quantity numeric,
    confidence_level text,
    created_at text not null
);

create table if not exists payments (
    id bigint generated by default as identity primary key,
    job_id text references jobs(job_id) on delete set null,
    raw_message_id bigint not null references raw_messages(id) on delete cascade,
    unit_number text,
    amount numeric,
    currency text default 'USD',
    status text,
    payer_name text,
    confidence_level text,
    created_at text not null
);

create table if not exists media_files (
    id bigint generated by default as identity primary key,
    raw_message_id bigint not null references raw_messages(id) on delete cascade,
    job_id text references jobs(job_id) on delete set null,
    media_type text,
    media_url text,
    local_path text,
    ocr_text text,
    processed_status text not null default 'pending',
    created_at text not null
);

create table if not exists alerts (
    id bigint generated by default as identity primary key,
    job_id text references jobs(job_id) on delete set null,
    raw_message_id bigint references raw_messages(id) on delete cascade,
    alert_type text not null,
    severity text not null,
    message text not null,
    status text not null default 'open',
    confidence_level text,
    created_at text not null,
    resolved_at text
);

create table if not exists settings (
    key text primary key,
    value text,
    updated_at text not null
);

create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    action text not null,
    entity_type text not null,
    entity_id text,
    details text,
    created_at text not null
);

create index if not exists idx_raw_messages_timestamp on raw_messages(timestamp);
create index if not exists idx_raw_messages_group on raw_messages(group_id);
create index if not exists idx_jobs_unit on jobs(unit_number);
create index if not exists idx_jobs_status on jobs(status);
create index if not exists idx_jobs_payment_status on jobs(payment_status);
create index if not exists idx_alerts_status on alerts(status);
create index if not exists idx_payments_unit on payments(unit_number);
